apiVersion: v1
kind: PersistentVolume
metadata:
  name: student12-nfs-pv  # Ex: student1-nfs-pv
  labels:
    name: student12-nfs-pv  # Ex: student1-nfs-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.142.15.238
    path: /
