apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:  # Make sure we claim our exact PV and not another students
    matchLabels:
      name: "student12-nfs-pv"
